### ISSUE TITLE
wget link not working

### ISSUE THREAD

**Issue by hbcbh1999** [google/FluidNet#11]
wget http://3d.csie.ntu.edu.tw/~dynamic/database/NTU3D.v1_0-999.zip
it seems this link no longer works.

**Comment by jonathantompson** [comment]
Ohh bummer. Yeah, and I can't host it (as a Google representative) for
licensing reasons. You might want to reach out to the original NTU3D
authors.

If you still can't find the file after reaching out to them, please email
me directly (tompson@google.com).

**Comment by joepareti54** [comment]
i have the same problem

**Comment by user-vm** [comment]
https://drive.google.com/open?id=0B-C8TTtLZczUSDlmNGEzc0EwdFk
