### ISSUE TITLE
what torch should be installed and how

### ISSUE THREAD

**Issue by joepareti54** [google/FluidNet#12]
From the documentation:

_We assume that Torch7 is installed, otherwise follow the instructions here. We use the standard distro with the cuda SDK for cutorch and cunn and cudnn._

So the above instructions take me to http://torch.ch/ which I used to install torch as per http://torch.ch/docs/getting-started.html#_

But presumably the standard distro (= https://github.com/torch/distro ) and cudnn (= https://github.com/soumith/cudnn.torch ) are additional or different components. 

Not knowing anything about torch I am fully in the dark as to which components should be installed. The documentation line I pasted above in italic is quite confusing

**Comment by jonathantompson** [comment]
Just built with the latest version of torch and added some notes to README.md.

Let me know if that's not enough info.
