### ISSUE TITLE
I can't access NTU 3D Model Database models 

### ISSUE THREAD

**Issue by jowoojun** [google/FluidNet#14]
I would like to run FluidNet but i can't access this link(http://3d.csie.ntu.edu.tw/~dynamic/database/).

So how can i download the model files??

When I tried to #1. Generating the data, I got this:

![image](https://user-images.githubusercontent.com/22931457/42671040-0bab4c70-8699-11e8-9183-82e10f5eea22.png)

**Comment by jonathantompson** [comment]
https://drive.google.com/open?id=0B-C8TTtLZczUSDlmNGEzc0EwdFk

**Comment by jonathantompson** [comment]
Also as per the readme, there's an alternate download location:

https://cs.nyu.edu/~schlacht/NTU3D.v1_0-999.zip
