### ISSUE TITLE
 Failed installing dependency:

### ISSUE THREAD

**Issue by joepareti54** [google/FluidNet#15]
the following command ends as per title line;

on this cloud I have neither wite permissions on /glob, nor sudo rights. I am trying a workaround using --local but it still fails, any ideas?
----
$ luarocks make tfluids-1-00.rockspec **--local**
...
make: *** [install] Error 1

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/torch-scm-1.rockspec - Build error: Failed installing.
[u23885@c009 tfluids]$ luarocks make tfluids-1-00.rockspec

Error: Your user does not have write permissions in /glob/deep-learning/versions/torch/install/lib/luarocks/rocks
-- you may want to run as a privileged user or use your local tree with --local.

**Comment by jonathantompson** [comment]
Sorry for the slow reply.

I ran through the instructions today and everything runs on my local machine.

If you want to submit a PR that fixes your issue please feel free to do so.
