### ISSUE TITLE
too few arguments in function call

### ISSUE THREAD

**Issue by chengcx1019** [google/FluidNet#9]
Sorry to bother you.When run this command

```
luarocks make tfluids-1-00.rockspec
```

I only get the error `FluidNet/torch/tfluids/generic/tfluids.cu(1882): error: too few arguments in function call`.

So I find this line in file,like this 

```
THCudaTensor_norm(state, tensor_pdelta_norm, tensor_pdelta, 2, 1);
```

Is there any change in function THCudaTensor_norm ?And  I'am in trouble with finding the definition of THCudaTensor_norm.

**Comment by jonathantompson** [comment]
Sorry for the slow response.  Did you figure out the issue?

**Comment by chengcx1019** [comment]
Yes,some kind of yes.the problem was caused by the update of cuotch,you can see the update in [this page](https://github.com/torch/cutorch/commit/9acf4d449de79ba23cf99266bb71879a8adbb548#diff-2a0907352bf194260ce5dc507e2f9ff7R179).It seems nothing else is influenced by this update except the function THCudaTensor_norm(here,FluidNet/torch/tfluids/generic/tfluids.cu(1882)).I assumed 1for Ture and 0 for False ,so I pass 1 as the sixth parameter，is this right?
